// <auto-generated />
using System;
using GestionProduccion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionProduccion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GestionProduccion.Domain.Entities.HistoricoProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataModificacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EtapaAnterior")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EtapaNova")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrdemProducaoId")
                        .HasColumnType("int");

                    b.Property<string>("StatusAnterior")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StatusNovo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdemProducaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistoricoProducoes");
                });

            modelBuilder.Entity("GestionProduccion.Domain.Entities.OrdemProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEstimadaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EtapaAtual")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("StatusAtual")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoUnico")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("OrdensProducao");
                });

            modelBuilder.Entity("GestionProduccion.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Email = "admin@local.host",
                            HashPassword = "$2a$11$pQ/exrK0i2CSUXyAID2ZqurDxpHYP1s6.H1MNELvp9AvjsTrYo2Bm",
                            Nome = "Administrador",
                            Perfil = "Administrador"
                        });
                });

            modelBuilder.Entity("GestionProduccion.Domain.Entities.HistoricoProducao", b =>
                {
                    b.HasOne("GestionProduccion.Domain.Entities.OrdemProducao", "OrdemProducao")
                        .WithMany("Historico")
                        .HasForeignKey("OrdemProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProduccion.Domain.Entities.Usuario", "UsuarioResponsavel")
                        .WithMany("AlteracoesNoHistorico")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemProducao");

                    b.Navigation("UsuarioResponsavel");
                });

            modelBuilder.Entity("GestionProduccion.Domain.Entities.OrdemProducao", b =>
                {
                    b.HasOne("GestionProduccion.Domain.Entities.Usuario", "UsuarioAtribuido")
                        .WithMany("OrdensAtribuidas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioAtribuido");
                });

            modelBuilder.Entity("GestionProduccion.Domain.Entities.OrdemProducao", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("GestionProduccion.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AlteracoesNoHistorico");

                    b.Navigation("OrdensAtribuidas");
                });
#pragma warning restore 612, 618
        }
    }
}
