using System.ComponentModel.DataAnnotations;

namespace GestionProduccion.Models.DTOs;

/// <summary>
/// DTO for requesting creation of a new Production Order.
/// </summary>
public class CreateProductionOrderRequest
{
    // LotCode is auto-generated by the system, so it is not included here.

    [Required(ErrorMessage = "Product is required.")]
    [Range(1, int.MaxValue, ErrorMessage = "A valid Product ID must be provided.")]
    public int ProductId { get; set; }

    [Required(ErrorMessage = "Quantity is required.")]
    [Range(1, int.MaxValue, ErrorMessage = "Quantity must be greater than 0.")]
    public int Quantity { get; set; }

    [Required(ErrorMessage = "Estimated completion date is required.")]
    public DateTime EstimatedCompletionAt { get; set; }

    [StringLength(100)]
    public string? ClientName { get; set; }

    [StringLength(20)]
    public string? Size { get; set; }

    public int? UserId { get; set; }

    public int? SewingTeamId { get; set; }
}
