/*
 * Copyright (c) 2026 David Fernandez Garzon. All rights reserved.
 * 
 * This software and its associated documentation files are the exclusive property 
 * of David Fernandez Garzon. Unauthorized copying, modification, distribution, 
 * or use of this software, via any medium, is strictly prohibited.
 * 
 * Proprietary and Confidential.
 */

using System.ComponentModel.DataAnnotations;

namespace GestionProduccion.Models.DTOs;

/// <summary>
/// DTO for requesting creation of a new Production Order.
/// </summary>
public class CreateProductionOrderRequest
{
    // LotCode is auto-generated by the system, so it is not included here.

    [Required(ErrorMessage = "Product is required.")]
    [Range(1, int.MaxValue, ErrorMessage = "A valid Product ID must be provided.")]
    public int ProductId { get; set; }

    [Required(ErrorMessage = "Quantity is required.")]
    [Range(1, int.MaxValue, ErrorMessage = "Quantity must be greater than 0.")]
    public int Quantity { get; set; }

    [Required(ErrorMessage = "Estimated completion date is required.")]
    public DateTime EstimatedCompletionAt { get; set; }

    [StringLength(100)]
    public string? ClientName { get; set; }

    [StringLength(20)]
    public string? Size { get; set; }

    public int? UserId { get; set; }

    public int? SewingTeamId { get; set; }

    /// <summary>
    /// Optional list of sizes and their quantities. 
    /// If provided, this overrides the single 'Size' and 'Quantity' fields.
    /// </summary>
    public List<ProductionOrderSizeRequest>? Sizes { get; set; } = new();
}

public class ProductionOrderSizeRequest
{
    [Required]
    [StringLength(20)]
    public string Size { get; set; } = string.Empty;

    [Range(1, int.MaxValue)]
    public int Quantity { get; set; }
}


